# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='academicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearOfJoining', models.IntegerField(max_length=4)),
                ('aggregate', models.IntegerField(max_length=10)),
                ('upperSecondaryInst', models.CharField(max_length=10)),
                ('upperSecondaryBoard', models.CharField(max_length=10)),
                ('upperSecondaryPercentage', models.IntegerField(max_length=10)),
                ('SecondaryInst', models.CharField(max_length=10)),
                ('SecondaryBoard', models.CharField(max_length=10)),
                ('SecondaryPercentage', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='additionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coAcademicActivities', models.CharField(max_length=30)),
                ('details', models.TextField(max_length=30)),
                ('coCurriculars', models.CharField(max_length=30)),
                ('hobbies', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('notification', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='personalInfo',
            fields=[
                ('rollNo', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('phone_no', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='notifications',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.personalInfo'),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.personalInfo'),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='student_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.personalInfo'),
        ),
    ]
