# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0002_auto_20170322_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='rollNo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
