language :python

python :
  -"3.5"
  
install :
    - pip install -r requriments.txt
    
    
services :
    - mysql
  
  
env:
    -Django=1.10 DB =mysql
  
  
before_script:
    -mysql  -e 'create database  dbdjango' -u root
    

script :
    - py.test tests.py











