language: python
python:
  - "3.5"

install:
    - pip install -r requirements.txt   
services:
  - mysql
  
env: 
      -DJANGO=1.10 DB=mysql

before_script: 
      - mysql -e 'create database dbdjango;' -u root
script: 
      - pytest tests.py


